version: '3.6'

services:
  my-mongodb:
    image: mongo:4.2.3-bionic
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=SDN_data
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    networks:
        - sdn-server-and-route-selection-mechanism_esnet1

networks:
  sdn-server-and-route-selection-mechanism_esnet1:
    external: true